name: waffle-api-backend
services:
  database:
    image: postgres:16.3
    ports:
      - 5000:5432
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: waffle_db
      POSTGRES_PASSWORD: 123
      POSTGRES_DATABASE: waffle_db
    networks:
      - app
    volumes:
      - ../docker/dbdata/pgdata:/var/lib/postgresql/data
  pgadmin:
    image: elestio/pgadmin:latest
    ports:
      - 8080:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: p@h.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 8080
    networks:
      - app
    volumes:
      - ../docker/dbdata/pgadmindata:/var/lib/pgadmin
networks:
  app:
    driver: bridge
